In [1]:
import numpy

In [4]:
?numpy.random.randint

In [100]:
arr1=numpy.random.randint(0,10,(4,2,3))
arr2=numpy.random.randint(0,10,(4,2,3))

In [103]:
print('arr1:\n',arr1,'\n','arr2:\n',arr2)

arr1:
 [[[9 2 6]
  [2 2 6]]

 [[8 4 0]
  [3 8 0]]

 [[0 1 1]
  [7 4 6]]

 [[9 6 8]
  [2 9 8]]] 
 arr2:
 [[[7 6 6]
  [2 0 9]]

 [[6 8 8]
  [6 3 7]]

 [[0 4 4]
  [4 8 2]]

 [[9 7 0]
  [8 3 5]]]


In [122]:
nb=arr2.reshape((-1,3)).reshape((-1),order='F')
#na=arr1.reshape(-1)
#print('na:\n',na)
print('nb:\n',nb)

nb:
 [7 2 6 6 0 4 9 8 6 0 8 3 4 8 7 3 6 9 8 7 4 2 0 5]


In [106]:
nb@na

577

In [53]:
a=arr1.reshape(8,3)
print(a)

[[8 2 4]
 [8 0 0]
 [7 1 8]
 [4 2 0]
 [2 6 3]
 [1 2 0]
 [6 9 3]
 [8 0 9]]


In [56]:
b=arr2.reshape(8,3)
print(b.T)

[[8 6 8 3 2 2 9 5]
 [2 8 6 1 1 6 8 1]
 [7 6 4 9 9 0 0 4]]


In [62]:
#这样会多计算 第二层卷积与图形的第一个channel点积
sum(numpy.dot(a,b.T))

array([585, 602, 592, 397, 353, 220, 572, 350])

In [61]:
#这样是符合卷积的计算的
sum(numpy.dot(b.T,a))

array([688, 319, 389])

In [26]:
arr1=arr1.reshape(1,12)

In [32]:
arr2=arr2.reshape(12,1)

In [33]:
print('arr1:\n',arr1,'\n','arr2:\n',arr2)

arr1:
 [[5 3 7 9 0 2 0 3 7 5 2 3]] 
 arr2:
 [[8]
 [9]
 [1]
 [9]
 [8]
 [8]
 [8]
 [1]
 [8]
 [0]
 [9]
 [3]]


In [34]:
numpy.dot(arr1,arr2)

array([[257]])

In [94]:
?numpy.reshape

In [99]:

arr=numpy.random.randint(0,10,(10,3,3,6))
arr

array([[[[3, 0, 9, 0, 9, 8],
         [1, 2, 3, 0, 8, 7],
         [2, 4, 7, 9, 0, 2]],

        [[3, 0, 4, 9, 7, 7],
         [0, 5, 0, 9, 8, 4],
         [1, 8, 9, 2, 0, 4]],

        [[2, 9, 0, 8, 5, 5],
         [8, 9, 1, 9, 9, 3],
         [7, 6, 5, 4, 6, 5]]],


       [[[8, 8, 6, 3, 7, 8],
         [4, 8, 3, 6, 4, 9],
         [2, 5, 4, 2, 2, 7]],

        [[8, 9, 0, 1, 6, 2],
         [8, 7, 0, 2, 4, 6],
         [7, 8, 9, 1, 7, 7]],

        [[9, 9, 1, 5, 4, 1],
         [1, 6, 2, 9, 5, 9],
         [7, 6, 3, 2, 7, 0]]],


       [[[3, 7, 3, 4, 1, 4],
         [1, 4, 5, 0, 9, 6],
         [3, 5, 2, 1, 7, 5]],

        [[2, 4, 1, 7, 5, 8],
         [6, 1, 3, 3, 3, 4],
         [3, 2, 3, 9, 1, 3]],

        [[6, 5, 6, 8, 9, 6],
         [1, 8, 6, 3, 3, 1],
         [0, 2, 9, 3, 6, 3]]],


       [[[5, 3, 3, 4, 0, 8],
         [9, 9, 8, 0, 7, 9],
         [5, 2, 4, 3, 8, 8]],

        [[7, 1, 0, 4, 2, 0],
         [2, 3, 0, 7, 4, 5],
         [4, 1, 7, 4, 2, 9]],

        [[5, 5,

In [108]:
arr.reshape((10,9,-1)).reshape((10,-1),order='F')

array([[3, 1, 2, 3, 0, 1, 2, 8, 7, 0, 2, 4, 0, 5, 8, 9, 9, 6, 9, 3, 7, 4,
        0, 9, 0, 1, 5, 0, 0, 9, 9, 9, 2, 8, 9, 4, 9, 8, 0, 7, 8, 0, 5, 9,
        6, 8, 7, 2, 7, 4, 4, 5, 3, 5],
       [8, 4, 2, 8, 8, 7, 9, 1, 7, 8, 8, 5, 9, 7, 8, 9, 6, 6, 6, 3, 4, 0,
        0, 9, 1, 2, 3, 3, 6, 2, 1, 2, 1, 5, 9, 2, 7, 4, 2, 6, 4, 7, 4, 5,
        7, 8, 9, 7, 2, 6, 7, 1, 9, 0],
       [3, 1, 3, 2, 6, 3, 6, 1, 0, 7, 4, 5, 4, 1, 2, 5, 8, 2, 3, 5, 2, 1,
        3, 3, 6, 6, 9, 4, 0, 1, 7, 3, 9, 8, 3, 3, 1, 9, 7, 5, 3, 1, 9, 3,
        6, 4, 6, 5, 8, 4, 3, 6, 1, 3],
       [5, 9, 5, 7, 2, 4, 5, 1, 6, 3, 9, 2, 1, 3, 1, 5, 7, 7, 3, 8, 4, 0,
        0, 7, 4, 7, 4, 4, 0, 3, 4, 7, 4, 1, 2, 4, 0, 7, 8, 2, 4, 2, 5, 6,
        2, 8, 9, 8, 0, 5, 9, 1, 4, 8],
       [6, 5, 1, 3, 9, 7, 4, 4, 2, 3, 8, 0, 9, 8, 7, 1, 7, 7, 8, 4, 5, 5,
        1, 9, 6, 1, 4, 7, 9, 9, 8, 4, 1, 3, 2, 7, 3, 4, 7, 7, 8, 9, 2, 4,
        7, 6, 1, 7, 3, 9, 2, 9, 4, 3],
       [9, 7, 5, 9, 9, 7, 8, 0, 6, 0, 4, 7, 5, 7, 0, 5, 6, 8, 7, 

In [32]:
arr.shape

(3, 3, 6)

In [36]:
carr=arr[0:2]

In [37]:
carr

array([[[3, 9, 7, 9, 8, 0],
        [4, 6, 5, 0, 6, 2],
        [1, 6, 1, 2, 6, 7]],

       [[3, 6, 9, 5, 7, 8],
        [3, 2, 4, 4, 2, 8],
        [1, 8, 5, 5, 7, 3]]])

In [38]:
carr[0]

array([[3, 9, 7, 9, 8, 0],
       [4, 6, 5, 0, 6, 2],
       [1, 6, 1, 2, 6, 7]])

In [39]:
carr[1]

array([[3, 6, 9, 5, 7, 8],
       [3, 2, 4, 4, 2, 8],
       [1, 8, 5, 5, 7, 3]])

In [40]:
carr[0][0]

array([3, 9, 7, 9, 8, 0])

In [41]:
carr[0][1]

array([4, 6, 5, 0, 6, 2])

In [42]:
carr[0][0:2]

array([[3, 9, 7, 9, 8, 0],
       [4, 6, 5, 0, 6, 2]])

In [46]:
q=carr[0:2,0:2,0:4]

In [47]:
q

array([[[3, 9, 7, 9],
        [4, 6, 5, 0]],

       [[3, 6, 9, 5],
        [3, 2, 4, 4]]])

In [77]:
p=q.reshape((-1,4)).reshape((-1,1),order='F')

In [79]:
p

array([[3],
       [4],
       [3],
       [3],
       [9],
       [6],
       [6],
       [2],
       [7],
       [5],
       [9],
       [4],
       [9],
       [0],
       [5],
       [4]])

In [72]:
p.T.shape

(16,)

In [56]:
w=p.reshape((-1,1))

In [70]:
w.T.shape

(1, 16)

In [66]:
numpy.dot(p,w)

array([493])

In [60]:
dd=p@w

In [81]:
fm=numpy.zeros((3,4))

In [82]:
fm

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
fm[2][2]=numpy.array(5)

In [90]:
fm

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 5., 0.]])

In [91]:
a=(3,4,6,8)
b=(4,8,9,90)

In [94]:
(3,43,6,8)+(4,8,9,90)

(3, 43, 6, 8, 4, 8, 9, 90)

In [1]:
import numpy

In [18]:
arr1=numpy.arange(240).reshape(4,4,3,5)

In [19]:
arr1.shape

(4, 4, 3, 5)

In [22]:
arr1[:,:,...,0].shape

(4, 4, 3)

In [14]:
arr2=arr1[:,1,1]

In [15]:
arr2=arr2.reshape((-1,1,1,5))

In [26]:
arr2.shape


(4, 1, 1, 5)